### ISSUE TITLE
What's the exactly time of punchard

### ISSUE THREAD

**Issue by snowman** [byn9826/commitsHours#1]
The https://api.github.com/repos/<user_name>/<repos_name>/stats/punch_card return JSON data, but what's the exactly time of that, recent week?

**Comment by snowman** [comment]
Yeah, There is not concept of the exactly time, the data is in increasing progress...

**Comment by byn9826** [comment]
@balalaXD  For this API, I believe it's all time data.
There might be other APIs provide data related to exact periods of time
https://developer.github.com/v3/repos/statistics/
